name: CI/CD Pipeline for Static Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      node-version: '16.x'
      build-directory: './build'

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      bucket-name: ${{ secrets.S3_BUCKET_NAME }}
      build-directory: './build'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
