- name: Deploy to AWS
  run: |
    aws s3 sync ./build s3://reusable-workflows-prac/ --delete
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
