name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      bucket-name:
        required: true
        type: string
      cloudfront-distribution-id:
        required: false
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://${{ inputs.bucket-name }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}

      - name: Invalidate CloudFront cache
        if: ${{ inputs.cloudfront-distribution-id }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront-distribution-id }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}
